# description
name: "Mad Skeleton"
description: "A small MADCSS-based web boilerplate"
keywords: "code, boilerplate, wireframe, assets, css, madcss"
author: "Leszek Pietrzak"

# address settings
baseurl: "http://mad-skeleton.smutnyleszek.com"
sourceurl: "https://github.com/smutnyleszek/mad-skeleton"
imagesPath: "/dist/images/"

# site configuration
safe: true
quiet: false
future: true
encoding: utf-8
markdown: kramdown
kramdown:
    auto_ids: false
timezone: Europe/Warsaw

# pull includes from other directory
includes_dir: src
exclude:
    # disabled src, as it breaks --watch (see includes_dir)
    # - src
    - bin
    - node_modules
    - LICENSE
    - README.md
    - package.json
